<a href="https://colab.research.google.com/github/niu2ben/program/blob/master/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**pytorch**
查看函数文档，查看函数源码

In [0]:
import torch as t
t.abs?

In [0]:
t.abs??

检查指令的执行时间

In [3]:
a = t.Tensor(3,4)
%timeit a.sum()

The slowest run took 8171.33 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 4.36 µs per loop


In [4]:
print(a.sum())

tensor(nan)


查看输入历史

In [5]:
%hist

import torch as t
t.abs?
t.abs??
a = t.Tensor(3,4)
%timeit a.sum()
print(a.sum())
%hist


In [7]:
%cat C:\Users\niuben\Desktop\wdsr_ntire2018-master\wdsr_a.py

cat: 'C:UsersniubenDesktopwdsr_ntire2018-masterwdsr_a.py': No such file or directory


In [8]:
%run -i C:\Users\niuben\Desktop\wdsr_ntire2018-master\wdsr_a.py

ERROR:root:File `'C:UsersniubenDesktopwdsr_ntire2018-masterwdsr_a.py'` not found.


In [9]:
%env

{'CLICOLOR': '1',
 'CLOUDSDK_CONFIG': '/content/.config',
 'COLAB_GPU': '0',
 'CUDA_PKG_VERSION': '10-0=10.0.130-1',
 'CUDA_VERSION': '10.0.130',
 'CUDNN_VERSION': '7.5.1.10',
 'DATALAB_SETTINGS_OVERRIDES': '{"kernelManagerProxyPort":6000,"kernelManagerProxyHost":"172.28.0.3","jupyterArgs":["--ip=\\"172.28.0.2\\""]}',
 'DEBIAN_FRONTEND': 'noninteractive',
 'ENV': '/root/.bashrc',
 'GCS_READ_CACHE_BLOCK_SIZE_MB': '16',
 'GIT_PAGER': 'cat',
 'GLIBCPP_FORCE_NEW': '1',
 'GLIBCXX_FORCE_NEW': '1',
 'HOME': '/root',
 'HOSTNAME': '2be3fa57ccbf',
 'JPY_PARENT_PID': '23',
 'LANG': 'en_US.UTF-8',
 'LAST_FORCED_REBUILD': '20190507',
 'LD_LIBRARY_PATH': '/usr/local/nvidia/lib:/usr/local/nvidia/lib64',
 'LD_PRELOAD': '/usr/lib/x86_64-linux-gnu/libtcmalloc.so.4',
 'LIBRARY_PATH': '/usr/local/cuda/lib64/stubs',
 'MPLBACKEND': 'module://ipykernel.pylab.backend_inline',
 'NCCL_VERSION': '2.4.2',
 'NO_GCE_CHECK': 'True',
 'NVIDIA_DRIVER_CAPABILITIES': 'compute,utility',
 'NVIDIA_REQUIRE_CUDA': 'cuda>=10.

**pytorch**入门

In [0]:
x = t.Tensor(5,3)

In [11]:
x

tensor([[5.7805e-36, 0.0000e+00, 4.4842e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.0524e+21, 6.7410e+22, 1.6596e-07],
        [8.4944e+20, 2.1669e-04, 6.6388e-07],
        [2.5788e-09, 8.3902e-07, 0.0000e+00]])

In [0]:
x = t.rand(5,3)

In [13]:
x

tensor([[0.9379, 0.4473, 0.0978],
        [0.5626, 0.1602, 0.3976],
        [0.2501, 0.2023, 0.5759],
        [0.8625, 0.3354, 0.4814],
        [0.8780, 0.5402, 0.6872]])

In [14]:
x.size()

torch.Size([5, 3])

In [23]:
x.shape

torch.Size([5, 3])

In [17]:
x[:,1]

tensor([0.4473, 0.1602, 0.2023, 0.3354, 0.5402])

In [0]:
b = x[1:3,1:3]

In [21]:
c = b.numpy()
c

array([[0.16021192, 0.39759547],
       [0.20233393, 0.57586646]], dtype=float32)

In [25]:
c.shape

(2, 2)

In [30]:
import numpy as np
a = np.ones(5)
b = t.from_numpy(a)
print(a,b)

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


tensor与numpy共享内存

In [31]:
b.add_(1)
print(a,b)

[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


**自动微分**Autograd